// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Command: typeof import('./../src/components/command/Command.vue')['default']
    CommandBody: typeof import('./../src/components/command/CommandBody.vue')['default']
    Commands: typeof import('./../src/components/command/commands/Commands.vue')['default']
    Item: typeof import('./../src/components/settings/Sub/Theme/Item.vue')['default']
    Navbar: typeof import('./../src/components/navbar/Navbar.vue')['default']
    ProjectCreatedView: typeof import('./../src/components/task/ProjectCreatedView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./../src/components/command/search/Search.vue')['default']
    SearchItem: typeof import('./../src/components/command/search/SearchItem.vue')['default']
    Selected: typeof import('./../src/components/settings/Sub/Theme/Selected.vue')['default']
    SettingsBody: typeof import('./../src/components/settings/SettingsBody.vue')['default']
    SettingsHeader: typeof import('./../src/components/settings/SettingsHeader.vue')['default']
    SettingsSidebar: typeof import('./../src/components/settings/SettingsSidebar.vue')['default']
    Smart: typeof import('./../src/components/settings/Sub/Smart/index.vue')['default']
    TaskEditor: typeof import('./../src/components/task/TaskEditor.vue')['default']
    TaskItem: typeof import('./../src/components/task/TaskItem.vue')['default']
    TaskLeftListProject: typeof import('./../src/components/task/TaskLeftListProject.vue')['default']
    TaskLeftListSmartProject: typeof import('./../src/components/task/TaskLeftListSmartProject.vue')['default']
    TaskLeftListView: typeof import('./../src/components/task/TaskLeftListView.vue')['default']
    TaskList: typeof import('./../src/components/task/TaskList.vue')['default']
    TheHeader: typeof import('./../src/components/header/TheHeader.vue')['default']
    Theme: typeof import('./../src/components/settings/Sub/Theme/index.vue')['default']
  }
}
